spring:
  application:
    name: dalston-eureka-provider
  zipkin:
    base-url: http://localhost:8001
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: password
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  cloud:
    config:
      #??????
      retry:
        initial-interval: 2000
        max-attempts: 2000
        max-interval: 2000
        multiplier: 1.2
      fail-fast: true
    bus:
      #??????
      refresh:
        enabled: true
      #??????
      trace:
        enabled: true
server:
  port: 2001
eureka:
  client:
    #Enable health check
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://127.0.0.1:1002/eureka
logging:
  level:
    com.ming.dao: debug
  file: ${spring.application.name}-${spring.profiles}.log
management:
  security:
    enabled: false
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh